package hibernateModel;
// Generated Nov 30, 2014 2:43:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer id;
     private String categoriename;
     private Set<Storeitems> storeitemses = new HashSet<Storeitems>(0);

    public Categories() {
    }

	
    public Categories(String categoriename) {
        this.categoriename = categoriename;
    }
    public Categories(String categoriename, Set<Storeitems> storeitemses) {
       this.categoriename = categoriename;
       this.storeitemses = storeitemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCategoriename() {
        return this.categoriename;
    }
    
    public void setCategoriename(String categoriename) {
        this.categoriename = categoriename;
    }
    public Set<Storeitems> getStoreitemses() {
        return this.storeitemses;
    }
    
    public void setStoreitemses(Set<Storeitems> storeitemses) {
        this.storeitemses = storeitemses;
    }




}


