package hibernateModel;
// Generated Nov 30, 2014 2:43:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String storename;
     private Set<Storeitems> storeitemses = new HashSet<Storeitems>(0);

    public Store() {
    }

	
    public Store(User user, String storename) {
        this.user = user;
        this.storename = storename;
    }
    public Store(User user, String storename, Set<Storeitems> storeitemses) {
       this.user = user;
       this.storename = storename;
       this.storeitemses = storeitemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getStorename() {
        return this.storename;
    }
    
    public void setStorename(String storename) {
        this.storename = storename;
    }
    public Set<Storeitems> getStoreitemses() {
        return this.storeitemses;
    }
    
    public void setStoreitemses(Set<Storeitems> storeitemses) {
        this.storeitemses = storeitemses;
    }




}


