package hibernateModel;
// Generated Nov 30, 2014 2:43:46 PM by Hibernate Tools 4.3.1



/**
 * Storeitems generated by hbm2java
 */
public class Storeitems  implements java.io.Serializable {


     private Integer id;
     private Categories categories;
     private Store store;
     private String price;
     private String description;
     private String photo1;
     private String photo2;
     private String photo3;
     private int quantity;

    public Storeitems() {
    }

    public Storeitems(Categories categories, Store store, String price, String description, String photo1, String photo2, String photo3, int quantity) {
       this.categories = categories;
       this.store = store;
       this.price = price;
       this.description = description;
       this.photo1 = photo1;
       this.photo2 = photo2;
       this.photo3 = photo3;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPhoto1() {
        return this.photo1;
    }
    
    public void setPhoto1(String photo1) {
        this.photo1 = photo1;
    }
    public String getPhoto2() {
        return this.photo2;
    }
    
    public void setPhoto2(String photo2) {
        this.photo2 = photo2;
    }
    public String getPhoto3() {
        return this.photo3;
    }
    
    public void setPhoto3(String photo3) {
        this.photo3 = photo3;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


